title: Oh No
author: dts04
email: delaneysiggia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaa
  aaaaAAAaaaAAAaaAaaaAAAAAAAAAAAAAAAAAaaaaaaaaaaaaAAAaaaaAAAaaaaaaaaaaA AAaaa
theme: minima

# social links
twitter_username: wbembii # DO NOT include the @ character, or else the build will fail!
github_username:  dts04 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
